### ISSUE TITLE
antivirus is blocking the mod from loading

### ISSUE THREAD

**Issue by playsi** [SSKirillSS/ram-compat#3]
![11Снимок экрана 2024-04-13 190228](https://github.com/SSKirillSS/ram-compat/assets/166938552/853e6eb7-5274-4748-b61f-c8d1a47b7cd2)
I can't download the curse forge mod, it's blocked by my antivirus.

**Comment by SSKirillSS** [comment]
![image](https://github.com/SSKirillSS/ram-compat/assets/38190325/8d135e83-2f40-4040-b6a3-d6afecf4ef7b)

Can't confirm this issue. Probably you have some weird configurations for your protection tools (like a fully blocked executable files or something similar).

**Comment by playsi** [comment]
but I can download the previous version of the mod
![Снимок экрана 2024-04-13 192431](https://github.com/SSKirillSS/ram-compat/assets/166938552/db67582f-ab3a-4386-8505-bfc820e9ae95)

**Comment by SSKirillSS** [comment]
This still means nothing. I've downloaded the latest version from CF and ran it through virustotal to be sure.

**Comment by playsi** [comment]
antivirus summary

![image](https://github.com/SSKirillSS/ram-compat/assets/166938552/2ade3da8-08a1-442e-b4e7-622d0e088a1d)
![image](https://github.com/SSKirillSS/ram-compat/assets/166938552/af6b3464-8c3a-439c-b150-942dddc3dcb1)
 
/

**Comment by playsi** [comment]
![image](https://github.com/SSKirillSS/ram-compat/assets/166938552/83993ec1-5a7d-4e0e-98ac-77919e3ef9c5)

**Comment by SSKirillSS** [comment]
Well, idk. It still looks like an issue of your protection tools. I've just decompiled .jar file, and it looks fine - code is valid, there is nothing third-party inside.

![image](https://github.com/SSKirillSS/ram-compat/assets/38190325/bf26b1aa-bbe8-47cc-8626-63a1118284af)

**Comment by playsi** [comment]
ok, thanks for the help
